version: '2.3'

services:
  reservations:
    build: .
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '4500:3002'

  database:
    build: db/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3